# Generated by Django 6.0.2 on 2026-02-26 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ig_id",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="ID в Instagram",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(verbose_name="Время создания в Instagram"),
                ),
                (
                    "db_created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время добавления в базу данных"
                    ),
                ),
                (
                    "caption",
                    models.TextField(
                        blank=True, default="", verbose_name="Текст поста"
                    ),
                ),
                (
                    "media_url",
                    models.URLField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Ссылка на медиа",
                    ),
                ),
                (
                    "permalink",
                    models.URLField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Ссылка на пост",
                    ),
                ),
                (
                    "db_updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время последнего обновленния в БД"
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="core_post_timesta_0d7300_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ig_id",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="ID в Instagram",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(verbose_name="Время создания в Instagram"),
                ),
                (
                    "db_created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время добавления в базу данных"
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст комментария")),
                ("username", models.CharField(max_length=100, verbose_name="Автор")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="core.post",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="core_commen_timesta_7b9dd4_idx"
                    )
                ],
            },
        ),
    ]
